config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :coaches

  root 'welcome#index'

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  validates :name, presence: true,
                    length: {minimum: 4 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
    @coaches = Coach.all
  end

  def show
    @coach = Coach.find(params[:id])
  end

  def new
    @coach = Coach.new
  end

  def edit
    @coach = Coach.find(params[:id])
  end

  def create
    # render plain: params [:coach].inspect
    # @coach = Coach.new(params.require(:coach).permit(:name, :tidbit))
    @coach = Coach.new(coach_params)

    if @coach.save
    redirect_to @coach
  else
    render 'new'
  end
end

  def update
    @coach = Coach.find(params[:id])
    if @coach.update(coach_params)
      redirect_to @coach
    else
      render 'edit'
    end
  end

  def destroy
    @coach = Coach.find(params[:id])
    @coach.destroy

    redirect_to coaches_path
  end

  private
    def coach_params
      params.require(:coach).permit(:name, :tidbit)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coaches/_form.html.erb
<%= form_for @coach do |f| %>

<% if @coach.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@coach.errors.countm "error") %>prohibited this coach from being saved:
  </h2>
  <ul>
    <% @coach.errors.full_messages.each do |msg| %>
    <li><%=msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :tidbit %><br>
  <%= f.text_field :tidbit %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/coaches/edit.html.erb
<h1>Edit This Coach</h1>
<%= render 'form' %>
<%= link_to 'Back', coaches_path %>


<!-- <%= form_for :coach, url: coach_path(@coach), method: :patch do |f| %>

  <% if @coach.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@coach.errors.count, "error") %> prohibited
        this coach from being saved:
      </h2>
      <ul>
        <% @coach.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name%><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :tidbits%><br>
    <%= f.text_area :tidbit %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', coaches_path %> -->

app/views/coaches/index.html.erb
<body>

<h1> Some NFL Head Coaches</h1>

<div id = 4> <%= link_to 'New coach', new_coach_path %> </div>
<table>
  <tr>
    <th>Name</th>
    <th>Tidbits</th>
    <th colspan="3"></th>
  </tr>

  <% @coaches.each do |coach| %>
    <tr>
      <td><%= coach.name %></td>
      <td><%= coach.tidbit %></td>
      <td><%= link_to 'Show', coach_path(coach) %></td>
      <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
      <td><%= link_to 'Destroy', coach_path(coach),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


</body>

app/views/coaches/new.html.erb
<h1> New Coach</h1>
<%= render 'form' %>
<%= link_to 'Back', coaches_path %>

<!-- <%= form_for :coach, url: coaches_path do |f| %>
#
# <% if @coach.errors.any? %>
# <div id ="error explanation">
#   <h2>
#     <%= pluralize(@coach.errors.count, "error") %> prohibited this coach from being saved:
#   </h2>
#   <ul>
#     <% @coach.errors.full_messages.each do |msg| %>
#     <li><%= msg %></li>
#
#     <% end %>
#   </ul>
# </div>
# <% end %>
#
#   <p>
#     <%= f.label :name %><br>
#     <%= f.text_field :name %>
#   </p>
#
#   <p>
#     <%= f.label :tidbit %><br>
#     <%= f.text_field :tidbit %>
#   </p>
#
#   <p>
#     <%= f.submit %>
#   </p>
# <% end %>
#
# <% link_to 'Back', coaches_path %> -->

app/views/coaches/show.html.erb
<p>
  <strong> Name:</strong>
  <%= @coach.name %>
</p>

<p>
  <strong> Tidbits:</strong>
  <%= @coach.tidbit %>
</p>


<%= link_to 'Back', coaches_path %> |

<%= link_to 'Edit', edit_coach_path(@coach) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coaching Facts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2> A Rudimntary Full-Stack App About NFL Head Coaches</h2>
<!-- <%  link_to 'Coaches Blog', controller: 'coaches' %> -->
<div id = 1><%= link_to 'Go To Coaches Database', coaches_path %></div>

<img src = "http://s32.postimg.org/enegx8f5h/bill_parcellsjpg_dfbf987e5f0f1860.jpg"></img>
<img src= "http://s32.postimg.org/4ybsw2185/1145756_1280x720.jpg"></img>